create table pauta (id bigint not null auto_increment, votacao_id bigint not null, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario (cpf bigint not null, id bigint not null auto_increment, email varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table votacao (data_inicio datetime(6) not null, duracao_minutos bigint not null, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table votacao_votos (votacao_id bigint not null, votos_id bigint not null) engine=InnoDB;
create table voto (voto bit, id bigint not null auto_increment, usuario_id bigint not null, votacao_id bigint not null, primary key (id)) engine=InnoDB;
alter table pauta add constraint UK_jk1ckc0xnt303vnopsauoqfx9 unique (votacao_id);
alter table votacao_votos add constraint UK_tg9l3rhasn7bq37ystelmd2ea unique (votos_id);
alter table pauta add constraint FK4nhp6h5ophrft1gnc6iaiyni2 foreign key (votacao_id) references votacao (id);
alter table votacao_votos add constraint FKsd0e2nw896y0g2o7vxa80usj8 foreign key (votos_id) references voto (id);
alter table votacao_votos add constraint FKbpw90sb8vlkyr3bh77j0sswh8 foreign key (votacao_id) references votacao (id);
alter table voto add constraint FKi9ulyrisn6f8ccd2lwpsbk382 foreign key (usuario_id) references usuario (id);
alter table voto add constraint FKryfcfaif7jtsd8tc7p04qyabt foreign key (votacao_id) references votacao (id);
